"""
EconoSphere AI -- Phase 11, Step 12: Adaptive Uncertainty Tests
======================================================================
File     : apps/api/tests/test_t1_adaptive_uncertainty.py
Purpose  : Comprehensive leakage, integrity and reproducibility tests
           for the Step 12 adaptive uncertainty pipeline.

Tests cover:
  - Data integrity (raw MD5, 2025 target NaN, no fabricated target)
  - Target leakage (excluded columns, no test/inference targets in calibration)
  - Temporal integrity (chronological splits, no future observations in stats)
  - Calibration integrity (Q90 from val only, country/volatility methods)
  - Mathematical validity (lower <= pred <= upper, finite values, positive width)
  - Reproducibility (deterministic script execution)
"""

import pytest
import hashlib
import json
import importlib.util
import sys
import numpy as np
import pandas as pd
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parents[3]
RAW_PATH     = PROJECT_ROOT / "data" / "raw" / "master_panel.csv"
INPUT_PATH   = PROJECT_ROOT / "data" / "processed" / "master_panel_t1_missingness.csv"
SCRIPT_PATH  = PROJECT_ROOT / "apps" / "api" / "ml" / "train_t1_adaptive_uncertainty.py"
FORECAST_PATH = PROJECT_ROOT / "data" / "processed" / "t1_step12_2026_forecasts.csv"
METADATA_PATH = PROJECT_ROOT / "models" / "phase11" / "t1_step12_uncertainty_metadata.json"

# Step 11 artifacts that must NOT be overwritten
STEP11_FORECAST = PROJECT_ROOT / "data" / "processed" / "t1_step11_2026_forecasts.csv"
STEP11_PRED     = PROJECT_ROOT / "data" / "processed" / "t1_step11_predictions.csv"
STEP11_META     = PROJECT_ROOT / "models" / "phase11" / "t1_step11_model_metadata.json"

EXPECTED_MD5  = "8ac7e0b2bf09fbe89289f82d0c7cf25e"
EXPECTED_Q90  = 11.4507
EXPECTED_RMSE = 3.9113
Q90_TOLERANCE  = 0.001
RMSE_TOLERANCE = 0.0001

FIVE_COUNTRIES = ["IND", "CHN", "USA", "JPN", "GBR"]

# ---------------------------------------------------------------------------
# Helper: load metadata (requires script to have been run first)
# ---------------------------------------------------------------------------
@pytest.fixture(scope="module")
def metadata():
    """Load Step 12 metadata JSON (must have been generated by running the script)."""
    if not METADATA_PATH.exists():
        pytest.skip("Step 12 metadata not found — run train_t1_adaptive_uncertainty.py first.")
    with open(METADATA_PATH) as f:
        return json.load(f)


@pytest.fixture(scope="module")
def forecast_df():
    """Load Step 12 2026 forecasts CSV."""
    if not FORECAST_PATH.exists():
        pytest.skip("Step 12 forecast CSV not found — run train_t1_adaptive_uncertainty.py first.")
    return pd.read_csv(FORECAST_PATH)


@pytest.fixture(scope="module")
def panel_df():
    """Load processed panel dataset."""
    return pd.read_csv(INPUT_PATH)


# ===========================================================================
# GROUP 1 — Data Integrity
# ===========================================================================

class TestDataIntegrity:
    """Verify raw data has not been modified."""

    def test_raw_md5_unchanged(self):
        """Raw master_panel.csv MD5 must exactly match 8ac7e0b2bf09fbe89289f82d0c7cf25e."""
        assert RAW_PATH.exists(), f"Raw data not found: {RAW_PATH}"
        computed = hashlib.md5(RAW_PATH.read_bytes()).hexdigest()
        assert computed == EXPECTED_MD5, (
            f"Raw data MD5 MISMATCH! Got: {computed}, Expected: {EXPECTED_MD5}"
        )

    def test_raw_dataset_unchanged(self):
        """Processed input must contain expected row counts."""
        df = pd.read_csv(INPUT_PATH)
        assert len(df) > 6000, "Processed dataset appears too small — possible corruption."

    def test_inference_2025_target_nan(self, panel_df):
        """2025 inference rows must have NaN gdp_growth_next_year (no fabricated target)."""
        inf = panel_df[panel_df["year"] == 2025]
        assert len(inf) > 0, "No 2025 rows found."
        assert inf["gdp_growth_next_year"].isna().all(), (
            "LEAKAGE: gdp_growth_next_year is NOT NaN for year=2025 rows!"
        )

    def test_no_fabricated_2026_target(self, panel_df):
        """There must be no year=2026 rows in the processed data."""
        assert (panel_df["year"] == 2026).sum() == 0, (
            "LEAKAGE: Fabricated 2026 target rows found in dataset!"
        )

    def test_step11_artifacts_not_overwritten(self):
        """Step 11 artifacts must still exist and be untouched."""
        assert STEP11_FORECAST.exists(), "Step 11 forecast CSV missing!"
        assert STEP11_PRED.exists(),     "Step 11 predictions CSV missing!"
        assert STEP11_META.exists(),     "Step 11 metadata JSON missing!"

    def test_step11_metadata_unchanged(self):
        """Step 11 metadata must still record the locked HistGradientBoosting model."""
        with open(STEP11_META) as f:
            meta = json.load(f)
        assert meta["selected_model"] == "A. HistGradientBoosting (Locked Control)"
        assert abs(meta["calibration_q90"] - EXPECTED_Q90) < Q90_TOLERANCE


# ===========================================================================
# GROUP 2 — Target Leakage
# ===========================================================================

class TestTargetLeakage:
    """Verify no target columns enter the feature matrix."""

    def test_gdp_growth_next_year_excluded_from_features(self):
        """gdp_growth_next_year must not appear in LOCKED_FEATURES."""
        content = SCRIPT_PATH.read_text()
        # Extract feature list between BASE_FEATURES = [ ... ] and ROLLING_EXTRA = [...]
        feature_section = content.split("BASE_FEATURES = [")[1].split("]")[0]
        assert "gdp_growth_next_year" not in feature_section, (
            "LEAKAGE: gdp_growth_next_year found in BASE_FEATURES!"
        )

    def test_gdp_growth_pct_excluded_from_features(self):
        """gdp_growth_pct must not appear in BASE_FEATURES."""
        content = SCRIPT_PATH.read_text()
        feature_section = content.split("BASE_FEATURES = [")[1].split("]")[0]
        assert "gdp_growth_pct" not in feature_section, (
            "LEAKAGE: gdp_growth_pct found in BASE_FEATURES!"
        )

    def test_next_year_target_available_excluded_from_features(self):
        """next_year_target_available must not appear in BASE_FEATURES."""
        content = SCRIPT_PATH.read_text()
        feature_section = content.split("BASE_FEATURES = [")[1].split("]")[0]
        assert "next_year_target_available" not in feature_section, (
            "LEAKAGE: next_year_target_available found in BASE_FEATURES!"
        )

    def test_no_test_targets_in_calibration(self):
        """Calibration functions must not use y_test or test-set targets."""
        content = SCRIPT_PATH.read_text()
        # The calibrate_* functions should reference y_val, not y_test
        # We check that test targets don't enter the calibration helpers
        assert "calibrate_global_q90(y_test" not in content, (
            "LEAKAGE: y_test passed into calibrate_global_q90!"
        )
        assert "calibrate_country_q90(test," not in content, (
            "LEAKAGE: test DataFrame passed into calibrate_country_q90!"
        )
        assert "calibrate_asymmetric_global(y_test" not in content, (
            "LEAKAGE: y_test passed into calibrate_asymmetric_global!"
        )
        assert "calibrate_country_asymmetric(test," not in content, (
            "LEAKAGE: test DataFrame passed into calibrate_country_asymmetric!"
        )

    def test_no_inference_targets_in_calibration(self):
        """Inference 2025 targets must not enter calibration."""
        content = SCRIPT_PATH.read_text()
        assert "calibrate_global_q90(y_inf" not in content
        assert "calibrate_country_q90(inf_2025," not in content
        assert "calibrate_asymmetric_global(y_inf" not in content

    def test_no_random_split(self):
        """train_test_split must not be used (only chronological splits)."""
        content = SCRIPT_PATH.read_text()
        assert "train_test_split" not in content, (
            "VIOLATION: Random train_test_split detected!"
        )

    def test_imputer_fitted_on_train_only(self):
        """Pipeline must be fit only on X_train."""
        content = SCRIPT_PATH.read_text()
        assert "pipe.fit(X_train, y_train)" in content, (
            "Pipeline must be fitted on X_train only!"
        )

    def test_no_test_gdp_growth_in_calibration_code(self):
        """Test-set GDP growth values must not be used to calculate any quantile."""
        content = SCRIPT_PATH.read_text()
        assert "np.quantile(y_test" not in content
        assert "np.abs(y_test" not in content


# ===========================================================================
# GROUP 3 — Temporal Integrity
# ===========================================================================

class TestTemporalIntegrity:
    """Verify strict chronological ordering of splits."""

    def test_train_before_validation(self, panel_df):
        """All train years must be strictly before all validation years."""
        # TRAIN_YEARS = (2000, 2018), VAL_YEARS = (2019, 2022)
        wba = {
            'AFE','AFW','ARB','CEB','CSS','EAP','EAR','EAS','ECA','ECS','EMU','EUU',
            'FCS','HIC','HPC','IBD','IBT','IDA','IDB','IDX','INX','LAC','LCN','LDC',
            'LIC','LMC','LMY','LTE','MEA','MIC','MNA','NAC','OED','OSS','PRE','PSS',
            'PST','SAS','SSA','SSF','SST','TEA','TEC','TLA','TMN','TSA','TSS','UMC','WLD'
        }
        df = panel_df[~panel_df["country_code"].isin(wba)]
        train_max = df[(df["year"] >= 2000) & (df["year"] <= 2018)]["year"].max()
        val_min   = df[(df["year"] >= 2019) & (df["year"] <= 2022)]["year"].min()
        assert train_max < val_min, f"Train max year ({train_max}) >= Val min year ({val_min})!"

    def test_validation_before_test(self, panel_df):
        """All validation years must be strictly before all test years."""
        wba = {
            'AFE','AFW','ARB','CEB','CSS','EAP','EAR','EAS','ECA','ECS','EMU','EUU',
            'FCS','HIC','HPC','IBD','IBT','IDA','IDB','IDX','INX','LAC','LCN','LDC',
            'LIC','LMC','LMY','LTE','MEA','MIC','MNA','NAC','OED','OSS','PRE','PSS',
            'PST','SAS','SSA','SSF','SST','TEA','TEC','TLA','TMN','TSA','TSS','UMC','WLD'
        }
        df = panel_df[~panel_df["country_code"].isin(wba)]
        val_max  = df[(df["year"] >= 2019) & (df["year"] <= 2022)]["year"].max()
        test_min = df[(df["year"] >= 2023) & (df["year"] <= 2024)]["year"].min()
        assert val_max < test_min, f"Val max ({val_max}) >= Test min ({test_min})!"

    def test_test_before_inference(self, panel_df):
        """Test years must be before inference year 2025."""
        test_max = panel_df[(panel_df["year"] >= 2023) & (panel_df["year"] <= 2024)]["year"].max()
        inf_min  = panel_df[panel_df["year"] == 2025]["year"].min()
        assert test_max < inf_min

    def test_no_overlap_train_val(self, panel_df):
        """Train and validation year ranges must not overlap."""
        train_years = set(panel_df[(panel_df["year"] >= 2000) & (panel_df["year"] <= 2018)]["year"])
        val_years   = set(panel_df[(panel_df["year"] >= 2019) & (panel_df["year"] <= 2022)]["year"])
        assert len(train_years & val_years) == 0

    def test_no_overlap_val_test(self, panel_df):
        """Validation and test year ranges must not overlap."""
        val_years  = set(panel_df[(panel_df["year"] >= 2019) & (panel_df["year"] <= 2022)]["year"])
        test_years = set(panel_df[(panel_df["year"] >= 2023) & (panel_df["year"] <= 2024)]["year"])
        assert len(val_years & test_years) == 0

    def test_volatility_computed_from_train_only(self):
        """The volatility calibration functions must use train_df, not val/test."""
        content = SCRIPT_PATH.read_text()
        # calibrate_volatility_groups takes train_df as first argument
        assert "calibrate_volatility_groups(train," in content
        # calibrate_volatility_scaled also uses train_df
        assert "calibrate_volatility_scaled(train," in content

    def test_no_future_data_in_volatility_calculation(self):
        """Volatility statistics must reference TRAIN data source only."""
        content = SCRIPT_PATH.read_text()
        # The functions calibrate_volatility_* should NOT accept val or test as first arg
        assert "calibrate_volatility_groups(val," not in content
        assert "calibrate_volatility_groups(test," not in content
        assert "calibrate_volatility_scaled(val," not in content
        assert "calibrate_volatility_scaled(test," not in content


# ===========================================================================
# GROUP 4 — Calibration Integrity
# ===========================================================================

class TestCalibrationIntegrity:
    """Verify each calibration method uses only appropriate data."""

    def test_global_q90_from_val_residuals(self):
        """Global Q90 calibration must use y_val and val predictions."""
        content = SCRIPT_PATH.read_text()
        assert "calibrate_global_q90(y_val, pred_val)" in content

    def test_country_q90_from_val_only(self):
        """Country Q90 must be calibrated from val DataFrame only."""
        content = SCRIPT_PATH.read_text()
        assert "calibrate_country_q90(val, pred_val)" in content

    def test_country_fallback_exists(self):
        """Country calibration must implement a fallback to global Q90."""
        content = SCRIPT_PATH.read_text()
        assert "global_q90" in content
        assert "country_q90_map.get(code, global_q90)" in content or \
               ".get(c, global_q90)" in content

    def test_volatility_thresholds_from_train(self):
        """Volatility group thresholds (p33/p67) must come from train σ only."""
        content = SCRIPT_PATH.read_text()
        assert "country_sigma = (" in content
        # The thresholds are computed from country_sigma which came from train_df
        assert "np.quantile(country_sigma.values, 1/3)" in content
        assert "np.quantile(country_sigma.values, 2/3)" in content

    def test_asymmetric_quantiles_from_val_only(self):
        """Asymmetric q10/q90 must be computed from validation signed residuals."""
        content = SCRIPT_PATH.read_text()
        assert "calibrate_asymmetric_global(y_val, pred_val)" in content
        assert "signed_residuals = y_val - pred_val" in content

    def test_no_test_residual_in_calibration(self):
        """No test residual calculation must enter any calibration function."""
        content = SCRIPT_PATH.read_text()
        assert "y_test - pred_test" not in content
        assert "np.abs(y_test - pred_test)" not in content

    def test_metadata_contains_q90(self, metadata):
        """Metadata must record the global Q90 close to expected 11.4507."""
        assert "exp_a_global_q90" in metadata
        assert abs(metadata["exp_a_global_q90"] - EXPECTED_Q90) < Q90_TOLERANCE

    def test_metadata_records_all_experiments(self, metadata):
        """Metadata must record validation and test results for all 6 experiments."""
        for split in ["validation_results", "test_results"]:
            assert split in metadata, f"Missing {split} in metadata"
            for exp in ["exp_a", "exp_b", "exp_c", "exp_d", "exp_e", "exp_f"]:
                assert exp in metadata[split], f"Missing {exp} in {split}"

    def test_promoted_method_recorded(self, metadata):
        """Metadata must record the final decision."""
        assert "final_decision" in metadata
        assert "promoted_method" in metadata
        assert metadata["final_decision"] != "", "final_decision must not be empty"

    def test_point_model_rmse_correct(self, metadata):
        """Point model Test RMSE in metadata must match the locked 3.9113."""
        assert "point_model_test_rmse" in metadata
        assert abs(metadata["point_model_test_rmse"] - EXPECTED_RMSE) < RMSE_TOLERANCE, (
            f"Point model RMSE mismatch: {metadata['point_model_test_rmse']:.4f} vs {EXPECTED_RMSE}"
        )


# ===========================================================================
# GROUP 5 — Mathematical Validity
# ===========================================================================

class TestMathematicalValidity:
    """Verify interval math is correct across all methods in the forecast CSV."""

    def test_forecast_csv_exists(self):
        """Step 12 forecast CSV must exist after script execution."""
        assert FORECAST_PATH.exists(), f"Forecast CSV not found: {FORECAST_PATH}"

    def test_forecast_required_columns(self, forecast_df):
        """Required columns must be present in forecast CSV."""
        required = [
            "country_code", "country_name", "feature_year", "target_year",
            "predicted_gdp_growth", "lower_bound_90", "upper_bound_90",
            "interval_width", "uncertainty_method",
        ]
        for col in required:
            assert col in forecast_df.columns, f"Missing column: {col}"

    def test_lower_le_predicted(self, forecast_df):
        """lower_bound_90 must be <= predicted_gdp_growth for all rows."""
        violators = forecast_df[forecast_df["lower_bound_90"] > forecast_df["predicted_gdp_growth"]]
        assert len(violators) == 0, (
            f"VIOLATION: lower_bound_90 > predicted_gdp_growth in {len(violators)} rows!"
        )

    def test_predicted_le_upper(self, forecast_df):
        """predicted_gdp_growth must be <= upper_bound_90 for all rows."""
        violators = forecast_df[forecast_df["predicted_gdp_growth"] > forecast_df["upper_bound_90"]]
        assert len(violators) == 0, (
            f"VIOLATION: predicted_gdp_growth > upper_bound_90 in {len(violators)} rows!"
        )

    def test_interval_width_correct(self, forecast_df):
        """interval_width must equal upper_bound_90 - lower_bound_90 (within float tol)."""
        expected_width = forecast_df["upper_bound_90"] - forecast_df["lower_bound_90"]
        diff = (forecast_df["interval_width"] - expected_width).abs()
        assert diff.max() < 1e-3, (
            f"interval_width inconsistency: max diff = {diff.max():.6f}"
        )

    def test_no_negative_widths(self, forecast_df):
        """All interval widths must be non-negative."""
        assert (forecast_df["interval_width"] >= 0).all(), (
            "VIOLATION: Negative interval width found!"
        )

    def test_all_values_finite(self, forecast_df):
        """All interval values must be finite (no NaN or Inf)."""
        for col in ["predicted_gdp_growth", "lower_bound_90", "upper_bound_90", "interval_width"]:
            assert np.isfinite(forecast_df[col].values).all(), (
                f"Non-finite values found in column: {col}"
            )

    def test_five_countries_in_forecast(self, forecast_df):
        """All 5 focal countries must appear in the forecast CSV."""
        for code in FIVE_COUNTRIES:
            assert (forecast_df["country_code"] == code).sum() > 0, (
                f"Country {code} not found in forecast CSV!"
            )

    def test_target_year_is_2026(self, forecast_df):
        """All forecast rows must have target_year = 2026."""
        assert (forecast_df["target_year"] == 2026).all()

    def test_feature_year_is_2025(self, forecast_df):
        """All forecast rows must have feature_year = 2025."""
        assert (forecast_df["feature_year"] == 2025).all()

    def test_metadata_q90_bounds(self, metadata):
        """All Q90 values in metadata must be positive."""
        assert metadata["exp_a_global_q90"] > 0
        for grp, q in metadata["exp_c_group_q90"].items():
            assert q > 0, f"Non-positive Q90 for volatility group {grp}"

    def test_metadata_asymmetric_sign_convention(self, metadata):
        """Asymmetric q10 must be negative (lower offset) and q90 must be positive (upper offset)."""
        q10 = metadata["exp_d_asym_q10"]
        q90 = metadata["exp_d_asym_q90"]
        assert q10 < q90, f"Asymmetric: q10={q10:.4f} must be < q90={q90:.4f}"

    def test_metadata_volatility_thresholds_ordered(self, metadata):
        """Volatility thresholds must be ordered: p33 < p67."""
        p33 = metadata["exp_c_vol_thresholds"]["p33"]
        p67 = metadata["exp_c_vol_thresholds"]["p67"]
        assert p33 < p67, f"Threshold ordering violated: p33={p33:.4f} >= p67={p67:.4f}"

    def test_coverage_values_in_range(self, metadata):
        """All empirical coverage values must be in [0, 1]."""
        for split in ["validation_results", "test_results"]:
            for exp_key, exp_res in metadata[split].items():
                cov = exp_res["empirical_coverage"]
                assert 0.0 <= cov <= 1.0, (
                    f"Coverage out of [0,1] for {exp_key} in {split}: {cov}"
                )


# ===========================================================================
# GROUP 6 — Reproducibility
# ===========================================================================

class TestReproducibility:
    """Verify that the pipeline produces deterministic results."""

    def test_script_exists(self):
        """The Step 12 script must exist."""
        assert SCRIPT_PATH.exists(), f"Script not found: {SCRIPT_PATH}"

    def test_metadata_exists(self):
        """The Step 12 metadata file must exist."""
        assert METADATA_PATH.exists()

    def test_locked_params_in_metadata(self, metadata):
        """Locked hyperparameters must match exactly the Step 10 specification."""
        params = metadata["locked_hyperparameters"]
        assert params["l2_regularization"] == 5.0
        assert params["learning_rate"]     == 0.05
        assert params["max_depth"]         == 5
        assert params["max_iter"]          == 300
        assert params["random_state"]      == 42

    def test_locked_features_in_metadata(self, metadata):
        """Feature list in metadata must match expected Step 8 feature count (31)."""
        features = metadata["locked_features"]
        assert len(features) == 31, (
            f"Expected 31 locked features, got {len(features)}"
        )

    def test_metadata_q90_matches_expected(self, metadata):
        """Global Q90 in metadata must match Step 11 control (11.4507)."""
        assert abs(metadata["exp_a_global_q90"] - EXPECTED_Q90) < Q90_TOLERANCE

    def test_uncertainty_methods_documented(self, forecast_df):
        """Forecast CSV must contain entries for multiple uncertainty methods."""
        methods = forecast_df["uncertainty_method"].unique()
        assert len(methods) >= 1, "Forecast CSV must contain at least one uncertainty method."

    def test_step12_not_overwriting_step11_metadata(self, metadata):
        """Step 12 metadata must be in a separate file from Step 11."""
        assert METADATA_PATH != STEP11_META
        assert METADATA_PATH.exists()
        assert STEP11_META.exists()

    def test_five_countries_point_forecasts_consistent(self, forecast_df):
        """Point forecasts must be identical for all methods for same country."""
        for code in FIVE_COUNTRIES:
            subset = forecast_df[forecast_df["country_code"] == code]
            if len(subset) > 1:
                pt_values = subset["predicted_gdp_growth"].values
                # All rows for same country should have same point forecast
                assert np.allclose(pt_values, pt_values[0], atol=1e-3), (
                    f"Point forecasts inconsistent for {code}: {pt_values}"
                )


# ===========================================================================
# GROUP 7 — Coverage Sanity (using metadata)
# ===========================================================================

class TestCoverageSanity:
    """Check that coverage results are scientifically plausible."""

    def test_control_val_coverage_documented(self, metadata):
        """Exp A validation coverage must be documented."""
        cov = metadata["validation_results"]["exp_a"]["empirical_coverage"]
        # We don't assert a specific value but it must be plausible (0.5-1.0)
        assert 0.5 <= cov <= 1.0, f"Implausible coverage: {cov}"

    def test_control_test_coverage_documented(self, metadata):
        """Exp A test coverage must be documented."""
        cov = metadata["test_results"]["exp_a"]["empirical_coverage"]
        assert 0.5 <= cov <= 1.0, f"Implausible test coverage: {cov}"

    def test_no_method_has_zero_coverage(self, metadata):
        """No method should have zero or near-zero coverage (catastrophic failure)."""
        for split in ["validation_results", "test_results"]:
            for exp_key, exp_res in metadata[split].items():
                cov = exp_res["empirical_coverage"]
                assert cov > 0.3, (
                    f"Coverage catastrophically low for {exp_key} in {split}: {cov:.4f}"
                )

    def test_interval_widths_positive(self, metadata):
        """All mean interval widths must be positive."""
        for split in ["validation_results", "test_results"]:
            for exp_key, exp_res in metadata[split].items():
                w = exp_res["mean_interval_width"]
                assert w > 0, f"Non-positive mean width for {exp_key} in {split}: {w}"

    def test_n_observations_positive(self, metadata):
        """All experiment evaluations must have positive N observations."""
        for split in ["validation_results", "test_results"]:
            for exp_key, exp_res in metadata[split].items():
                n = exp_res["n_observations"]
                assert n > 0, f"Zero observations for {exp_key} in {split}"

    def test_decision_is_valid_option(self, metadata):
        """Final decision must be one of the two valid outcomes."""
        decision = metadata["final_decision"]
        valid_decisions = [
            "KEEP STEP 11 GLOBAL Q90 CONTROL",
        ]
        # Accept any string starting with PROMOTE or being the KEEP decision
        is_valid = (
            decision.startswith("PROMOTE") or
            decision == "KEEP STEP 11 GLOBAL Q90 CONTROL"
        )
        assert is_valid, f"Invalid decision recorded: '{decision}'"
