from abc import ABC, abstractmethod
from typing import Dict, Any, Optional

GlobalState = Dict[str, Dict[str, Any]]
ShockVector = Dict[str, Dict[str, float]]


class SimulationStrategy(ABC):
    """Base strategy for propagating shocks across a specific domain (e.g., Trade, Banking)."""

    @abstractmethod
    def apply_shock(self, state: GlobalState, initial_shocks: ShockVector, config: dict, dependency_map: Optional[Dict[str, Any]] = None) -> ShockVector:
        """
        Takes the current global state, initial shock vectors, and optional topological dependency map.
        Returns a dictionary of new, calculated shocks generated by this strategy.
        """
        pass


class IndicatorCalculator(ABC):
    """Base calculator for translating propagated domain shocks into macroeconomic KPIs."""

    @abstractmethod
    def calculate(self, state: GlobalState, applied_shocks: ShockVector) -> GlobalState:
        """
        Mutates the global state by applying the net effects of the shocks to KPIs.
        Returns the updated global state.
        """
        pass
