"""Add simulation models

Revision ID: 89c84394de95
Revises: scenario_status_manual
Create Date: 2026-07-23 14:28:26.753094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89c84394de95'
down_revision: Union[str, Sequence[str], None] = 'scenario_status_manual'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PAUSED', name='simulationstatus'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_id'), 'simulation_runs', ['id'], unique=False)
    op.create_table('simulation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', name='logseverity'), nullable=False),
    sa.Column('affected_country', sa.String(), nullable=True),
    sa.Column('affected_indicator', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_logs_id'), 'simulation_logs', ['id'], unique=False)
    op.create_table('simulation_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('global_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active_shocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_snapshots_id'), 'simulation_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_countries_iso3'), 'countries', ['iso3'], unique=False)
    op.alter_column('scenario_events', 'parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    op.drop_column('scenario_versions', 'notes')
    op.alter_column('scenarios', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenarios', 'description',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('scenario_versions', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('scenario_events', 'parameters',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_countries_iso3'), table_name='countries')
    op.drop_index(op.f('ix_simulation_snapshots_id'), table_name='simulation_snapshots')
    op.drop_table('simulation_snapshots')
    op.drop_index(op.f('ix_simulation_logs_id'), table_name='simulation_logs')
    op.drop_table('simulation_logs')
    op.drop_index(op.f('ix_simulation_runs_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    # ### end Alembic commands ###
