"""Add Scenario Models

Revision ID: e1161522f790
Revises: e3f3f11caa73
Create Date: 2026-07-21 22:25:09.591954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1161522f790'
down_revision: Union[str, Sequence[str], None] = 'e3f3f11caa73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('parent_event_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('ECONOMIC', 'POLITICAL', 'ENVIRONMENTAL', 'FINANCIAL', 'HEALTH', 'ENERGY', 'TECHNOLOGY', 'SUPPLY_CHAIN', name='eventcategory'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DISABLED', 'ARCHIVED', name='eventstatus'), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('shockIntensity', sa.Float(), nullable=True),
    sa.Column('propagationDelay', sa.Integer(), nullable=True),
    sa.Column('recoveryRate', sa.Float(), nullable=True),
    sa.Column('affectedNodes', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('simulationWeight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['parent_event_id'], ['scenario_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['scenario_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_events')
    op.drop_table('scenario_versions')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
