"""Initial migration

Revision ID: e3f3f11caa73
Revises: 
Create Date: 2026-07-21 21:47:09.968484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f3f11caa73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('iso3', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('income_group', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('iso3')
    )
    op.create_index(op.f('ix_countries_iso3'), 'countries', ['iso3'], unique=False)
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=False)
    op.create_index(op.f('ix_countries_region'), 'countries', ['region'], unique=False)
    op.create_table('countries_metadata',
    sa.Column('iso3', sa.String(length=3), nullable=False),
    sa.Column('capital', sa.String(length=255), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=50), nullable=True),
    sa.Column('flag_url', sa.String(length=1024), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['iso3'], ['countries.iso3'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('iso3')
    )
    op.create_table('historical_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iso3', sa.String(length=3), nullable=True),
    sa.Column('indicator_name', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['iso3'], ['countries.iso3'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_indicators_indicator_name'), 'historical_indicators', ['indicator_name'], unique=False)
    op.create_index(op.f('ix_historical_indicators_iso3'), 'historical_indicators', ['iso3'], unique=False)
    op.create_index(op.f('ix_historical_indicators_year'), 'historical_indicators', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_indicators_year'), table_name='historical_indicators')
    op.drop_index(op.f('ix_historical_indicators_iso3'), table_name='historical_indicators')
    op.drop_index(op.f('ix_historical_indicators_indicator_name'), table_name='historical_indicators')
    op.drop_table('historical_indicators')
    op.drop_table('countries_metadata')
    op.drop_index(op.f('ix_countries_region'), table_name='countries')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_index(op.f('ix_countries_iso3'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
